### ISSUE TITLE
v2.63.14: /api/usage returns 404 for valid paths while /api/resources succeeds

### ISSUE THREAD

**Issue by yfzhou0904** [filebrowser/filebrowser#5985]
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
v2.63.14
```

### Description

After upgrading to v2.63.14, the disk usage endpoint started returning `404 Not Found` for valid FileBrowser paths.

This is reproducible on my live deployment with the `admin` user. The same paths work through `/api/resources` but fail through `/api/usage`, so the paths themselves are valid in FileBrowser.

### What did you expect to happen?

I expected `/api/usage` to return usage information for valid directories.

### What actually happened?

`/api/usage` returns `404 Not Found` for valid paths that `/api/resources` can list successfully.

Verified against my live instance:

- `GET /api/resources/root/downloads` -> `200`
- `GET /api/usage/root/downloads` -> `404`
- `GET /api/resources/mnt/blockstorage/downloads` -> `200`
- `GET /api/usage/mnt/blockstorage/downloads` -> `404`

The authenticated user is:
- username: `admin`
- scope: `.`

My FileBrowser container mounts host `/` to container `/srv`, so these in-app paths should resolve to real on-disk paths under `/srv/...`.

This appears to be a regression introduced by commit `7c2c0a11` (`refactor: ScopedFs to avoid escaping symlinks`).

Root cause analysis:
- before the refactor, `d.user.Fs` was `*afero.BasePathFs`
- after the refactor, `d.user.Fs` became `*files.ScopedFs`
- `FileInfo.RealPath()` only resolves through `RealPath(name)` if the filesystem implements it
- `ScopedFs` in v2.63.14 does not implement `RealPath()`
- so `file.RealPath()` falls back to the FileBrowser path (for example `/root/downloads`) instead of the real on-disk path (for example `/srv/root/downloads`)
- `diskUsage` passes that path into disk usage collection / `Statfs`
- that path does not exist on the container filesystem, so it fails with `ENOENT`
- `errToStatus` maps that to `404`

I verified this against a clean `v2.63.14` checkout. Adding this method to `ScopedFs` restores the expected behavior:

```go
func (s *ScopedFs) RealPath(name string) (string, error) {
    return s.base.RealPath(name)
}
```

### Reproduction Steps

1. Deploy FileBrowser `v2.63.14` in Docker with host `/` mounted to container `/srv`.
2. Log in as `admin` with scope `.`.
3. Request a valid directory through `/api/resources`, for example:
   - `/api/resources/root/downloads`
   - `/api/resources/mnt/blockstorage/downloads`
4. Confirm those requests return `200`.
5. Request usage for the same directories through `/api/usage`.
6. Observe that those requests return `404 Not Found`.

### Files

Relevant files:
- `users/users.go`
- `files/scoped.go`
- `files/file.go`
- `http/resource.go`
- `http/utils.go`

Relevant commit:
- `7c2c0a11` (`refactor: ScopedFs to avoid escaping symlinks`)
